spring:
  datasource:
    jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  batch:
    job:
      enabled: false
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
