spring:
  datasource:
    batch:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
      continue-on-error: false
    pulley:
      jdbc-url: jdbc:h2:mem:pulley;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
    mathflat:
      jdbc-url: jdbc:h2:mem:pulley;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
  batch:
    initialize-schema: always
    job:
      enabled: false
  h2:
    console:
      enabled: true