spring:
  datasource:
    batch:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
      continue-on-error: false
    pulley:
      jdbc-url: jdbc:mysql://mathflat-renewal-dev.ce1us4oyptfa.ap-northeast-2.rds.amazonaws.com:3306/iclass
      username: admin
      password: 12345678!
      driver-class-name: com.mysql.cj.jdbc.Driver
      continue-on-error: false
    mathflat:
      jdbc-url: jdbc:mysql://mathflat-renewal-dev.ce1us4oyptfa.ap-northeast-2.rds.amazonaws.com:3306/iclass
      username: admin
      password: 12345678!
      driver-class-name: com.mysql.cj.jdbc.Driver
      continue-on-error: false
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
  batch:
    initialize-schema: always
    job:
      enabled: false
  h2:
    console:
      enabled: true